### PR TITLE
Support flash attention 2 with causal masking when KV's seq length is…

### PR DESCRIPTION
**Pull request by BoxiangW**
… longer than Q's seq length.

Support causal masking like:
111000
111100
111110
111111
where Q's seq length is 5 while KV's seq length is 6.

### CODE REVIEW

**Comment by tridao** [comment]
Thanks! This is only the forward pass right? 
I thought about it a bit and I think we'll need to be quite careful about correctness. There could be cases where we need causal masking on 2 blocks (currently because of the assumption of causal, we only need to check 1 block).
The other concern is performance: it should not affect performance for the common use case of causal attention when seqlen_q = seqlen_k.

**Comment by BoxiangW** [comment]
I changed both forward pass and backward pass, and tried a few tests about the correctness. 
For the first concern are you talking about 2 blocks like 
|1110|0000|
|1111|1000|
    1       2     ?
I tested this situation and the result matrix was correct.
About the second concern, I think my implementation will not affect the performance since the algo was not affected.

**Comment by sz128** [comment]
> … longer than Q's seq length.
> 
> Support causal masking like: 111000 111100 111110 111111 where Q's seq length is 5 while KV's seq length is 6.

Does it support arbitrary masking like:
[
100000
110000
001000
001100
000010
000011
,
100000
110000
111000
000100
000110
000111
]
, where batch_size=2, Q\K\V seq_length=6 ?

**Comment by BoxiangW** [comment]
> > … longer than Q's seq length.
> 
> > 
> 
> > Support causal masking like: 111000 111100 111110 111111 where Q's seq length is 5 while KV's seq length is 6.
> 
> 
> 
> Does it support arbitrary masking like:
> 
> [
> 
> 100000
> 
> 110000
> 
> 001000
> 
> 001100
> 
> 000010
> 
> 000011
> 
> ,
> 
> 100000
> 
> 110000
> 
> 111000
> 
> 000100
> 
> 000110
> 
> 000111
> 
> ]
> 
> , where batch_size=2, Q\K\V seq_length=6 ?

For this PR no.

**Comment by siddartha-RE** [comment]
Just wanted to let you know that I tested this branch against my version of the FastChat monkey patch. I confirmed it was working as expected:
https://github.com/siddartha-RE/FastChat.flashpatch/commit/6ad40e9f8aca571971859f480b7a5bc9183209c3

The change makes sense to me in that there is basically still one block that will be mixed (0 and 1) in terms of the causal mask. The position of the block just gets shifted because we have chopped off a set of trailing q vectors. It doesn't seem it impacts anything other than adjusting the calculation of where the cross over block falls.

**Comment by tridao** [comment]
I'm working on this this week. I also want it to work for when seqlen_q > seqlen_k, so there quite a few edge cases.

**Comment by tridao** [comment]
> For q_len > k_len and causal=True how will you handle the q positions that cannot see any of the k positions? For example the 0th position when q_len = k_len + 1. That will have to be a NaN output right?

Output will be 0 for that case.

 > Separately, just wanted to mention that I tested the change in the PR together with my change enabling flash_attn + use_cache = True on a real world dataset of 16K prompts. I saw an amazing speed up of at least 20x! We are very excited to get this into production.

That's some crazy speedup!

**Comment by siddartha-RE** [comment]
> > For q_len > k_len and causal=True how will you handle the q positions that cannot see any of the k positions? For example the 0th position when q_len = k_len + 1. That will have to be a NaN output right?
> 
> Output will be 0 for that case.
> 

If thats the case (ie it will be constant 0) shouldn't it just be illegal to be q_len > k_len?

**Comment by siddartha-RE** [comment]
> > > For q_len > k_len and causal=True how will you handle the q positions that cannot see any of the k positions? For example the 0th position when q_len = k_len + 1. That will have to be a NaN output right?
> > 
> > 
> > Output will be 0 for that case.
> 
> If thats the case (ie it will be constant 0) shouldn't it just be illegal to be q_len > k_len?

Meaning If is_causal then q_len > k_len is illegal since the output for [0, q_len - k_len] == 0.

**Comment by TsingWei** [comment]
Does it support blocked causal mask like:
110000
111100
111111,
where tokens are grouped in causal?

**Comment by tridao** [comment]
No it doesn't. What's the use case?

**Comment by TsingWei** [comment]
Just an idea suddenly came to mind that, if we use a ViT encoder for a video sequence.  The tokens from one frame are in one group, and the ViT encoder can be combined with a group casual map for a video task.

**Comment by jxjalsq** [comment]
why impl flash attention v2 , spilt q, k, v with block size =1,  it pricision is 10*e-2, the error is so big? when v is not fuse to onlinesftmax , is ok?

**Comment by jxjalsq** [comment]
i impl flash attention in cpp code, and run in android, please resolve this problem， thank you.@

**Comment by jxjalsq** [comment]
> No it doesn't. What's the use case?

hello

**Pull request merged**
