### PR TITLE
enable checkpointing for gpt model def'n

### PR DESCRIPTION
**Pull request by lxuechen**

### CODE REVIEW

**Comment by lxuechen** [comment]
Initial benchmarking shows that gradient checkpointing doesn't bring noticeable differences when flash-attention is enabled. This makes sense as flash-attention does activation recomputation.

**Comment by tmm1** [comment]
How do you mean? Generally checkpoints will trade slower speed for much less memory usage, no?

**Comment by tmm1** [comment]
I am interested in checkpointing support to reduce VRAM requirements. But I don't quite understand how this PR works. Is there something using `checkpointing` kwarg already?

**Comment by tmm1** [comment]
This change was not enough for me to use with HF trainer:

>AttributeError: 'GPTLMHeadModel' object has no attribute 'gradient_checkpointing_enable'

**Comment by lxuechen** [comment]
> This change was not enough for me to use with HF trainer:
> 
> > AttributeError: 'GPTLMHeadModel' object has no attribute 'gradient_checkpointing_enable'

This is because trainer calls `model.gradient_checkpointing_enable`, but `gradient_checkpointing_enable` is function of Tri's model definition. 

To answer your question above as to why I don't expect setting `checkpointing = True` further saves memory when flash-attention is turned on: This is because Tri is checkpointing the attention portion, but FlashAttention already avoids storing activations in the attention block and performs backwards recomputation (this is documented in [the original paper](https://arxiv.org/pdf/2205.14135.pdf)).

**Pull request closed without merging**
