### PR TITLE
Support blocked KV cache for flash decoding

### PR DESCRIPTION
**Pull request by beginlner**
Restriction: `block_size` must match `kBlockN` in the kernel.

### CODE REVIEW

**Comment by tridao** [comment]
Hi @beginlner I have a commit implementing paged KV cache based on some on the ideas in this PR, can I add you as co-author of the commit?

**Comment by beginlner** [comment]
> Hi @beginlner I have a commit implementing paged KV cache based on some on the ideas in this PR, can I add you as co-author of the commit?

Hi @tridao Sure, I'd be happy to be added as a co-author on your commit.

**Comment by masahi** [comment]
@tridao Is there a possibility to support smaller block sizes than 256?

**Comment by tridao** [comment]
> @tridao Is there a possibility to support smaller block sizes than 256?

Sure, we just need someone interested in working on that.

**Comment by skrider** [comment]
@tridao I work with the vLLM project a bit and we are super interested in this feature getting implemented, so I took a stab at it here: https://github.com/Dao-AILab/flash-attention/pull/824 . Would greatly appreciate a review.

**Pull request closed without merging**
